name: Unit Tests

on:
  workflow_dispatch:

  push:
    paths:
      - "bin/**"
      - "package*.json"
      - "workers/**"
      - "lib/**"
      - "cdk.json"
      - "tsconfig.json"

    branches-ignore:
      - main
      - dev

jobs:
  unit-test:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment:
      name: development

    env:
      NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
      FRONTEND_DOMAIN_URL: ${{ secrets.FRONTEND_DOMAIN_URL }}
      BACKEND_WEBHOOK_URL: ${{ secrets.BACKEND_WEBHOOK_URL }}
      GITHUB_ORG: ${{ github.repository_owner }}
      GITHUB_REPO: ${{ github.event.repository.name }}
      CLOUDFRONT_DOMAIN_NAME: ${{ secrets.CLOUDFRONT_DOMAIN_NAME }}
      CLOUDFRONT_DOMAIN_CERTIFICATE_ARN: ${{ secrets.CLOUDFRONT_DOMAIN_CERTIFICATE_ARN }}
      CLOUDFRONT_PUBLIC_KEY: ${{ secrets.CLOUDFRONT_PUBLIC_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Decode CloudFront public key
        run: |
          echo "${{ secrets.CLOUDFRONT_PUBLIC_KEY }}" | base64 -d > cf-public-key.pem
          echo "${{ secrets.CLOUDFRONT_PUBLIC_KEY }}" | base64 -d > test/public-key.pem

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Run Synth
        run: cdk synth

      - name: Stack Changes
        run: cdk diff

  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [unit-test]
    if: always()
    steps:
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1.16.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ needs.unit-test.result == 'success' && 'success' || 'failure' }}
          title: Unit Test Results
          description: |
            **Commit:** ${{ github.event.head_commit.message }}
            **Triggered by:** ${{ github.actor }}
            **Branch:** ${{ github.ref_name }}
            **Repository:** ${{ github.repository }}
          url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
